import type { PlatformRole, PlatformPermission, PlatformUser } from '../types/auth.types';

export const ROLE_PERMISSIONS: Record<PlatformRole, PlatformPermission[]> = {
  'Platform Owner': ['*'],
  'Super Admin': [
    'Dashboard.View',
    'Tenant.View',
    'Tenant.Create',
    'Tenant.Edit',
    'Tenant.Delete',
    'Support.View',
    'Support.Manage',
    'Security.View',
    'Security.Manage',
    'AuditLog.View',
  ],
  'Finance Admin': [
    'Dashboard.View',
    'Tenant.View',
    'Billing.View',
    'Billing.Manage',
    'AuditLog.View',
  ],
  'Support Admin': [
    'Dashboard.View',
    'Tenant.View',
    'Support.View',
    'Support.Manage',
  ],
  'Auditor': [
    'Dashboard.View',
    'Tenant.View',
    'AuditLog.View',
    'Security.View',
  ],
};

export const MOCK_USERS: Record<string, PlatformUser> = {
  owner: {
    id: 'usr_owner_01',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@internalops.io',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    role: 'Platform Owner',
    permissions: ROLE_PERMISSIONS['Platform Owner'],
    status: 'Active',
    department: 'Executive Office',
    mfaEnabled: true,
    lastLoginAt: new Date().toISOString(),
  },
  superadmin: {
    id: 'usr_sadmin_02',
    name: 'Michael Chen',
    email: 'michael.chen@internalops.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    role: 'Super Admin',
    permissions: ROLE_PERMISSIONS['Super Admin'],
    status: 'Active',
    department: 'Infrastructure Operations',
    mfaEnabled: true,
    lastLoginAt: new Date().toISOString(),
  },
  finance: {
    id: 'usr_finance_03',
    name: 'Elena Rostova',
    email: 'elena.rostova@internalops.io',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    role: 'Finance Admin',
    permissions: ROLE_PERMISSIONS['Finance Admin'],
    status: 'Active',
    department: 'Global Billing & Finance',
    mfaEnabled: true,
    lastLoginAt: new Date().toISOString(),
  },
  support: {
    id: 'usr_support_04',
    name: 'David Kalu',
    email: 'david.kalu@internalops.io',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    role: 'Support Admin',
    permissions: ROLE_PERMISSIONS['Support Admin'],
    status: 'Active',
    department: 'Customer Success Operations',
    mfaEnabled: false,
    lastLoginAt: new Date().toISOString(),
  },
  auditor: {
    id: 'usr_auditor_05',
    name: 'Marcus Vance',
    email: 'marcus.vance@internalops.io',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    role: 'Auditor',
    permissions: ROLE_PERMISSIONS['Auditor'],
    status: 'Active',
    department: 'Risk & Compliance',
    mfaEnabled: true,
    lastLoginAt: new Date().toISOString(),
  },
};
